title: Shivam Yadav
description: Data Scientist & ML Enthusiast
site_title: '@yshivam - Shivam Yadav'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: shivamyadav00
# blog_url: 
email: shivam@yadav.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/yadav.shivam.jpeg

# Google Analytics ID
google_analytics: 